### ISSUE TITLE
Symlink error 

### ISSUE THREAD

**Issue by Shashi456** [jamigibbs/phantom#11]
The file ```/_layouts/defaults.html``` has a symlink which does not exist in the ```_includes``` directory, namely two files ```title.html``` and ```title-group.html``` .

**Comment by NotAnyMike** [comment]
Any solution?

**Comment by guiemi** [comment]
Same problem here.

**Comment by shingkid** [comment]
Same issue - `tile.html` and `title-group.html` are missing from the `_includes` directory.

**Comment by wjia26** [comment]
same
