### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by rob-nash** [jamigibbs/phantom#6]
Hi,

Just going through the README step by step and run into this.

```
Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
jekyll 3.7.3 | Error:  jekyll-paginate
```

**Comment by jamigibbs** [comment]
Hi @rob-nash ,

That error suggest that you might not have installed the theme dependencies yet. Can you try running `npm install` before running jekyll.

**Comment by jamigibbs** [comment]
Following up, realized NPM shouldn't be needed for this project (sorry, it's an old one for me and I haven't given it much attention in a while).

I'll see about updating to resolve those warnings (including #7 ). Likely will require a different pagination plugin so I'm not sure when I'll be able to test a new one. In the mean time, you can always remove the pagination from `_config.yml`
